### ISSUE TITLE
Terraform 12 has breaking syntax changes for this repo

### ISSUE THREAD

**Issue by rbavery** [anoff/vm-automation#1]
following the guidance here, the new version of terraform has a command `terraform 0.12upgrade` that rewrites the terraform scripts to fix the old syntax

https://www.terraform.io/upgrade-guides/0-12.html

Without running this, you'll get an error like this

```
(base) (master)~/CropMask_RCNN/terraform$ terraform apply

Error: Unsupported block type

  on azure_dsvm.tf line 180, in resource "azurerm_public_ip" "ds":
 180:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.


```

**Comment by anoff** [comment]
was fixed by your PR #3 :)
